# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NkBwycrtTm9eE-bzu5bhM6VoCi1oTuc3
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

#Parameters
n_values = [10, 50, 200]
Nsim = 10000
np.random.seed(42)

# Store results
means = []
variances = []

#Simulations and plots
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
for idx, n in enumerate(n_values):
    # Simulate Bernoulli samples
    X = np.random.binomial(1, 0.5, size=(Nsim, n))
    # Compute sums
    S_n = X.sum(axis=1)
    # Standardize
    Z_n = (S_n - n/2) / np.sqrt(n/4)
    # Empirical statistics
    emp_mean = np.mean(Z_n)
    emp_var = np.var(Z_n)
    means.append(emp_mean)
    variances.append(emp_var)
    # Histogram
    axes[idx].hist(
        Z_n,
        bins=30,
        density=True,
        alpha=0.7,
        label='Simulated'
    )
    # Standard Normal Density
    x = np.linspace(-4, 4, 500)
    axes[idx].plot(
        x,
        norm.pdf(x),
        linewidth=2,
        label='N(0,1)'
    )
    axes[idx].set_title(f'n = {n}')
    axes[idx].set_xlabel('$Z_n$')
    axes[idx].set_ylabel('Density')
    axes[idx].legend()
    axes[idx].grid(True)
plt.suptitle('Empirical CLT for Bernoulli(0.5)')
plt.tight_layout()
plt.show()

#part g
print("Empirical Statistics")
print("-"*50)
for n, m, v in zip(n_values, means, variances):
    print(
        f"n = {n:3d} -> "
        f"Mean = {m:.4f} -> "
        f"Variance = {v:.4f}"
    )