# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJzkivhw2GVyNFucat6sTlnsgETVVE2C

1.e
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

np.random.seed(42)

T = 1.0
N = 10000
dt = T / N
# Brownian increments
dW = np.random.normal(
    loc=0,
    scale=np.sqrt(dt),
    size=N
)
# Brownian path
W = np.concatenate(
    ([0], np.cumsum(dW))
)
time = np.linspace(0, T, N + 1)
# Increments
increments = np.diff(W)
# Quadratic variation
QV = np.sum(increments**2)
# Total variation
TV = np.sum(np.abs(increments))
print(f"Empirical Quadratic Variation : {QV:.6f}")
print(f"Theoretical Value (T)         : {T:.6f}")
print(f"Absolute Error                : {abs(QV-T):.6f}")

# Plot Brownian path
plt.figure(figsize=(10,4))
plt.plot(
    time,
    W,
    linewidth=0.7,
    color="steelblue"
)
plt.axhline(
    0,
    linestyle="--",
    color="black",
    linewidth=0.8
)
plt.title(
    f"Brownian Motion Path (N={N})\n"
    f"QV={QV:.4f}, TV={TV:.2f}"
)
plt.xlabel("Time")
plt.ylabel(r"$W_t$")
plt.grid(alpha=0.3)

"""1.f"""

N_values = [10,50,100,500,1000,5000,10000]
qv_values = []

np.random.seed(42)
N_fine = 10000
dt_fine = T / N_fine
dW_fine = np.random.normal(
    0,
    np.sqrt(dt_fine),
    N_fine
)
W_fine = np.concatenate(
    ([0], np.cumsum(dW_fine))
)
for N_part in N_values:
    step = N_fine // N_part
    W_sub = W_fine[::step]
    inc = np.diff(W_sub)
    qv = np.sum(inc**2)
    qv_values.append(qv)
    print(
        f"N = {N_part:5d} | "
        f"QV = {qv:.6f}"
    )
print()
print(
    "As N increases, empirical quadratic variation "
    "approaches T=1."
)
print(
    "The fluctuations decrease roughly at rate "
    "O(sqrt(dt))."
)
plt.figure(figsize=(8,5))
plt.semilogx(
    N_values,
    qv_values,
    marker="o",
    linewidth=2,
    label="Empirical QV"
)
plt.axhline(
    y=T,
    color="red",
    linestyle="--",
    linewidth=2,
    label="Theoretical QV = 1"
)
plt.xlabel("Number of Partition Steps (log scale)")
plt.ylabel("Quadratic Variation")
plt.title(
    "Convergence of Quadratic Variation"
)
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

np.random.seed(42)
n_paths = 10000
T = 1.0
N_sim = 1000
dt = T / N_sim
t_fixed = 0.5
idx = round(t_fixed / dt)
# Simulate all paths simultaneously
dW_all = np.random.normal(
    0,
    np.sqrt(dt),
    size=(n_paths, N_sim)
)
W_all = np.hstack(
    (
        np.zeros((n_paths, 1)),
        np.cumsum(dW_all, axis=1)
    )
)
W_t = W_all[:, idx]
emp_mean = np.mean(W_t)
emp_var = np.var(W_t)
print(
    f"Empirical Mean      = {emp_mean:.5f}"
)
print(
    f"Theoretical Mean    = 0"
)
print()
print(
    f"Empirical Variance  = {emp_var:.5f}"
)
print(
    f"Theoretical Variance= {t_fixed}"
)
# Histogram
x = np.linspace(-3, 3, 500)
plt.figure(figsize=(8,5))
plt.hist(
    W_t,
    bins=60,
    density=True,
    alpha=0.6,
    color="steelblue",
    label="Simulated Samples"
)
plt.plot(
    x,
    norm.pdf(
        x,
        loc=0,
        scale=np.sqrt(t_fixed)
    ),
    color="red",
    linewidth=2,
    label=r"Theoretical $N(0,t)$"
)
plt.title(
    r"Distribution of $W_{0.5}$"
)
plt.xlabel(r"$W_{0.5}$")
plt.ylabel("Density")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()









































