# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1He_DgPM2e0BOvLG0Gww2_iBGBN3r6UVY

**Q1: Portfolio Loss Dependence**
*Simulates 10000 observations of (IA, IB) with conditional dependence structure.*
"""

import numpy as np
np.random.seed(42)
# Given probabilities
P_LB = 0.20
P_LA = 0.10
P_LA_given_LB = 0.35

# Derived quantities
P_LA_and_LB = P_LA_given_LB * P_LB  # = 0.07
P_LA_given_LBc = (P_LA - P_LA_and_LB) / (1 - P_LB)  # = (0.10 - 0.07) / 0.80 = 0.0375

# Theoretical values
P_LA_union_LB = P_LA + P_LB - P_LA_and_LB  # = 0.23
E_N = P_LA + P_LB  # = 0.30

# Var(N) = Var(IA) + Var(IB) + 2*Cov(IA,IB)
Var_IA = P_LA * (1 - P_LA)  # = 0.09
Var_IB = P_LB * (1 - P_LB)  # = 0.16
Cov_IA_IB = P_LA_and_LB - P_LA * P_LB  # = 0.07 - 0.02 = 0.05
Var_N = Var_IA + Var_IB + 2 * Cov_IA_IB  # = 0.35

print("=" * 60)
print("THEORETICAL VALUES")
print("=" * 60)
print(f"P(LA intersection LB)          = {P_LA_and_LB:.4f}")
print(f"P(LA union LB)          = {P_LA_union_LB:.4f}")
print(f"P(LA | LB^c)        = {P_LA_given_LBc:.4f}")
print(f"E[N]                = {E_N:.4f}")
print(f"Var(N)              = {Var_N:.4f}")
print(f"Cov(IA, IB)         = {Cov_IA_IB:.4f}")

# Simulation
n_sim = 10000
IB = np.random.binomial(1, P_LB, size=n_sim)
IA = np.zeros(n_sim)

for i in range(n_sim):
    if IB[i] == 1:
        IA[i] = np.random.binomial(1, P_LA_given_LB)
    else:
        IA[i] = np.random.binomial(1, P_LA_given_LBc)

N = IA + IB

# Simulation estimates
sim_P_intersection = np.mean(IA * IB)
sim_P_union = np.mean((IA + IB) >= 1)
sim_E_N = np.mean(N)
sim_Var_N = np.var(N, ddof=0)

print("\n" + "=" * 60)
print("SIMULATION ESTIMATES (n = 10000)")
print("=" * 60)
print(f"P(LA ∩ LB) estimate = {sim_P_intersection:.4f}  (theoretical: {P_LA_and_LB:.4f})")
print(f"P(LA ∪ LB) estimate = {sim_P_union:.4f}  (theoretical: {P_LA_union_LB:.4f})")
print(f"E[N] estimate       = {sim_E_N:.4f}  (theoretical: {E_N:.4f})")
print(f"Var(N) estimate     = {sim_Var_N:.4f}  (theoretical: {Var_N:.4f})")

# Independence comparison
P_joint_indep = P_LA * P_LB
factor = P_LA_and_LB / P_joint_indep
print(f"\nUnder independence: P(LA ∩ LB) = {P_joint_indep:.4f}")
print(f"True / Independent ratio      = {factor:.2f}")
print(f"Independence underestimates by factor {factor:.1f}x")





















