# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCeK_bIHoyxvOYL360PKK9-Qg_FeeF8v
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import lognorm, norm

np.random.seed(42)
S0 = 100
mu = 0.07
sigma = 0.2
T = 1
N = 500
dt = T / N
n_paths = 50000

"""2.c"""

t = 10
correct_mean = S0 * np.exp(mu * t)
wrong_mean = S0 * np.exp(
    mu * t + 0.5 * sigma**2 * t
)
error_pct = (
    (wrong_mean - correct_mean)
    / correct_mean
) * 100
print("Correct E[S_t] =", round(correct_mean, 2))
print("Wrong E[S_t]   =", round(wrong_mean, 2))
print("Percentage Error =", round(error_pct, 2), "%")

"""2.d"""

dW = np.random.normal(
    0,
    np.sqrt(dt),
    size=(n_paths, N)
)
S = np.zeros((n_paths, N + 1))
S[:, 0] = S0
for k in range(N):
    S[:, k + 1] = (
        S[:, k]
        + mu * S[:, k] * dt
        + sigma * S[:, k] * dW[:, k]
    )
ST = S[:, -1]
# Theoretical Lognormal Density
log_mean = np.log(S0) + (
    mu - 0.5 * sigma**2
) * T
log_std = sigma * np.sqrt(T)
x = np.linspace(
    ST.min(),
    ST.max(),
    500
)
plt.figure(figsize=(8, 5))
plt.hist(
    ST,
    bins=100,
    density=True,
    alpha=0.6,
    label="Simulated"
)
plt.plot(
    x,
    lognorm.pdf(
        x,
        s=log_std,
        scale=np.exp(log_mean)
    ),
    linewidth=2,
    label="Theoretical Lognormal"
)
plt.title("Terminal Stock Price Distribution")
plt.xlabel(r"$S_T$")
plt.ylabel("Density")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""2.e"""

emp_mean = np.mean(ST)
emp_std = np.std(ST)
theo_mean = S0 * np.exp(mu * T)
theo_std = (
    S0 * np.exp(mu * T)
    * np.sqrt(
        np.exp(sigma**2 * T) - 1
    )
)
print(
    "Empirical Mean =",
    round(emp_mean, 4)
)
print(
    "Theoretical Mean =",
    round(theo_mean, 4)
)
print(
    "Empirical Std =",
    round(emp_std, 4)
)
print(
    "Theoretical Std =",
    round(theo_std, 4)
)

"""2.f"""

K = 110
for sig in [0.1, 0.3, 0.5]:
    ST_vol = S0 * np.exp(
        (mu - 0.5 * sig**2) * T
        + sig * np.random.normal(
            0,
            np.sqrt(T),
            n_paths
        )
    )
    payoff = np.mean(
        np.maximum(ST_vol - K, 0
    )
    )
    print(f"\nsigma = {sig}")
    print(
        "Mean =",
        round(np.mean(ST_vol), 2)
    )
    print(
        "Std =",
        round(np.std(ST_vol), 2)
    )
    print(
        "E[(S_T-K)+] =",
        round(payoff, 2)
    )

"""2.g"""

log_returns = np.log(ST / S0)
emp_mean_lr = np.mean(log_returns)
emp_var_lr = np.var(log_returns)
theo_mean_lr = (
    mu - 0.5 * sigma**2
) * T
theo_var_lr = sigma**2 * T
print(
    "Empirical Mean =",
    round(emp_mean_lr, 4)
)
print(
    "Theoretical Mean =",
    round(theo_mean_lr, 4)
)
print(
    "Empirical Variance =",
    round(emp_var_lr, 4)
)
print(
    "Theoretical Variance =",
    round(theo_var_lr, 4)
)

"""log return hist"""

x = np.linspace(
    log_returns.min(),
    log_returns.max(),
    500
)
plt.figure(figsize=(8, 5))
plt.hist(
    log_returns,
    bins=80,
    density=True,
    alpha=0.6,
    label="Simulated"
)
plt.plot(
    x,
    norm.pdf(
        x,
        theo_mean_lr,
        np.sqrt(theo_var_lr)
    ),
    linewidth=2,
    label="Normal Density"
)
plt.title("Distribution of Log Returns")
plt.xlabel(r"$\log(S_T/S_0)$")
plt.ylabel("Density")
plt.legend()
plt.grid(alpha=0.3)
plt.show()