# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TDUDnFG3wIG_AOjI5rpQJcH9u8BjD5r-
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import quad

#true value of the integral
f = lambda x: np.exp(-x**2)
I_true, _ = quad(f, 0, 1)
print(f"True Integral Value = {I_true:.8f}")

#Monte Carlo Estimates
N_values = [10**2, 10**3, 10**4, 10**5]
estimates = []
errors = []
np.random.seed(42)
for N in N_values:
    # Generate Uniform(0,1) samples
    U = np.random.uniform(0, 1, N)
    # Monte Carlo estimate
    I_hat = np.mean(np.exp(-U**2))
    # Absolute error
    error = abs(I_hat - I_true)
    estimates.append(I_hat)
    errors.append(error)
    print(
        f"N = {N:6d} -> "
        f"Estimate = {I_hat:.8f} -> "
        f"Absolute Error = {error:.8f}"
    )

#Plot estimates vs. N
plt.figure(figsize=(8,5))
plt.semilogx(
    N_values,
    estimates,
    marker='o',
    linewidth=2,
    label='Monte Carlo Estimate'
)
plt.axhline(
    I_true,
    linestyle='--',
    linewidth=2,
    label='True Value'
)
plt.xlabel("Sample Size N")
plt.ylabel("Integral Estimate")
plt.title(r"Monte Carlo Estimation of $\int_0^1 e^{-x^2}\,dx$")
plt.legend()
plt.grid(True)
plt.show()

#Plot absolute error vs N
plt.figure(figsize=(8,5))
plt.loglog(
    N_values,
    errors,
    marker='o',
    linewidth=2
)
plt.xlabel("Sample Size N")
plt.ylabel("Absolute Error")
plt.title("Monte Carlo Error vs Sample Size")
plt.grid(True)
plt.show()

#summary

print("\nSummary")
for N, est, err in zip(N_values, estimates, errors):
    print(
        f"N={N:6d} -> "
        f"Estimate={est:.8f} -> "
        f"Error={err:.8f}"
    )





