# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sC4sF-UQ5-6JiGnwaS0PsMKzG1qm-xoU

**Q2: Credit Rating Migration**
*Simulates a Markov chain for credit rating transitions.*
"""

import numpy as np
np.random.seed(42)
# Transition matrix
P = np.array([
    [0.60, 0.25, 0.05, 0.10],
    [0.00, 0.50, 0.50, 0.00],
    [0.00, 0.50, 0.50, 0.00],
    [0.00, 0.00, 0.00, 1.00]
])

state_names = {0: "Investment Grade", 1: "Speculative Grade",
               2: "Distressed", 3: "Default"}

print("Transition Matrix P:")
print(P)
print()

#g: Simulate one path of 100 steps from state 0
def simulate_chain(P, start, n_steps):
    """Simulate a Markov chain path."""
    states = [start]
    current = start
    for _ in range(n_steps):
        current = np.random.choice(len(P), p=P[current])
        states.append(current)
    return np.array(states)

path = simulate_chain(P, start=0, n_steps=100)
print("SINGLE PATH SIMULATION (100 steps from state 0)")
print(f"First 20 states: {path[:21]}")
print(f"Final state: {state_names[path[-1]]}")
print()

#h: 1000 simulations, proportions at time 100
n_sims = 1000
n_steps = 100
final_states = np.zeros(n_sims, dtype=int)

for i in range(n_sims):
    path_i = simulate_chain(P, start=0, n_steps=n_steps)
    final_states[i] = path_i[-1]

prop_default = np.mean(final_states == 3)
prop_class12 = np.mean((final_states == 1) | (final_states == 2))

print(f"1000 SIMULATIONS (100 steps from state 0)")
print(f"Proportion in state 3 (Default) at t=100:   {prop_default:.4f}")
print(f"Proportion in class {{1,2}} at t=100:         {prop_class12:.4f}")
print(f"Proportion in state 0 at t=100:              {np.mean(final_states == 0):.4f}")
print()

#Stationary distributions
#Closed class {3}: stationary dist = (0, 0, 0, 1)
#Closed class {1,2}: restricted matrix [[0.5, 0.5],[0.5, 0.5]]
#Solving pi * P_restricted = pi: pi1 = pi2 = 0.5
#Full: (0, 0.5, 0.5, 0)

print("STATIONARY DISTRIBUTIONS")
print("Closed class {3}:    pi = (0, 0, 0, 1)")
print("Closed class {1,2}:  pi = (0, 0.5, 0.5, 0)")
print("General stationary:  pi = alpha*(0, 0.5, 0.5, 0) + (1-alpha)*(0, 0, 0, 1)")
print("                     for any alpha in [0, 1]")

# Verify with matrix power
P100 = np.linalg.matrix_power(P, 100)
print(f"\nP^100 (row 0 = long-run distribution starting from state 0):")
print(P100[0])

















