# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HFCRDb0Y7KE9a-dU3TiJP0lNC9uh2Q0
"""

import numpy as np
import matplotlib.pyplot as plt

#part b and c
N_values = [10**2, 10**3, 10**4, 10**5]
pi_estimates = []
for N in N_values:
    # Generate random points in [-1,1] x [-1,1]
    x = np.random.uniform(-1, 1, N)
    y = np.random.uniform(-1, 1, N)
    # Check if points lie inside the unit circle
    inside = (x**2 + y**2) <= 1
    # Estimate pi
    pi_hat = 4 * np.mean(inside)
    pi_estimates.append(pi_hat)
    print(f"N = {N:6d}  -> Estimated π = {pi_hat:.6f}")

#part d
N_plot = 5000
x = np.random.uniform(-1, 1, N_plot)
y = np.random.uniform(-1, 1, N_plot)
inside = (x**2 + y**2) <= 1
plt.figure(figsize=(8,8))
plt.scatter(
    x[inside],
    y[inside],
    s=5,
    label='Inside Circle'
)
plt.scatter(
    x[~inside],
    y[~inside],
    s=5,
    label='Outside Circle'
)
theta = np.linspace(0, 2*np.pi, 500)
plt.plot(
    np.cos(theta),
    np.sin(theta),
    linewidth=2,
    label='Unit Circle'
)
plt.xlim(-1.05, 1.05)
plt.ylim(-1.05, 1.05)
plt.xlabel("x")
plt.ylabel("y")
plt.title("Monte Carlo Simulation for π")
plt.legend()
plt.axis('equal')
plt.grid(True)
plt.show()

#part e
plt.figure(figsize=(8,5))
plt.semilogx(
    N_values,
    pi_estimates,
    marker='o',
    linewidth=2,
    label='Estimated π'
)
plt.axhline(
    np.pi,
    linestyle='--',
    linewidth=2,
    label='True π'
)
plt.xlabel("Number of Samples (N)")
plt.ylabel("Estimate of π")
plt.title("Monte Carlo Estimate of π vs Sample Size")
plt.legend()
plt.grid(True)
plt.show()

#part g
print("\nComparison with true value:")
print(f"True π = {np.pi:.6f}")
for N, est in zip(N_values, pi_estimates):
    error = abs(est - np.pi)
    print(
        f"N = {N:6d} -> Estimate = {est:.6f} -> "
        f"Absolute Error = {error:.6f}"
    )