# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qPN4h-z8LSeEzQ1VsuxIuY0GJS-TzwGt
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
np.random.seed(42)

#parameters
X0 = 3.0
theta = 2.0
sigma = 0.5
T = 5
N = 5000
dt = T / N
time = np.linspace(0, T, N + 1)

"""3.d"""

stationary_std = sigma / np.sqrt(2 * theta)
plt.figure(figsize=(9,5))
for _ in range(10):
    X = np.zeros(N + 1)
    X[0] = X0
    for k in range(N):
        dW = np.random.normal(
            0,
            np.sqrt(dt)
        )
        X[k+1] = (
            X[k]
            - theta * X[k] * dt
            + sigma * dW
        )
    plt.plot(time, X, alpha=0.7)
plt.axhline(
    0,
    linestyle="--",
    color="black",
    label="Stationary Mean"
)
plt.fill_between(
    time,
    -2 * stationary_std,
    2 * stationary_std,
    alpha=0.15,
    label="±2 Stationary Std"
)
plt.title("Ornstein-Uhlenbeck Paths")
plt.xlabel("Time")
plt.ylabel(r"$X_t$")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""3.e"""

n_paths = 20000
T_long = 10
N_long = 10000
dt_long = T_long / N_long
X = np.full(n_paths, X0)
for k in range(N_long):
    dW = np.random.normal(
        0,
        np.sqrt(dt_long),
        n_paths
    )
    X = (
        X
        - theta * X * dt_long
        + sigma * dW
    )
terminal_values = X
emp_mean = np.mean(terminal_values)
emp_var = np.var(terminal_values)
theo_var = sigma**2 / (2 * theta)
print("\nPart (e)")
print("Empirical Mean =", round(emp_mean,4))
print("Theoretical Mean = 0")
print("Empirical Variance =", round(emp_var,4))
print("Theoretical Variance =", round(theo_var,4))
x = np.linspace(-1.5,1.5,500)
plt.figure(figsize=(8,5))
plt.hist(
    terminal_values,
    bins=80,
    density=True,
    alpha=0.6,
    label="Simulated"
)
plt.plot(x,norm.pdf(
        x,
        0,
        np.sqrt(theo_var)
    ),
    linewidth=2,
    label="Theoretical Normal"
)
plt.title("Stationary Distribution")
plt.xlabel(r"$X_T$")
plt.ylabel("Density")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""3.f"""

thetas = [0.5, 2.0, 5.0]
fig, axes = plt.subplots(
    1,
    3,
    figsize=(14,4),
    sharey=True
)
for ax, th in zip(axes, thetas):
    stat_std = sigma / np.sqrt(2 * th)
    for _ in range(5):
        X = np.zeros(N + 1)
        X[0] = X0
        for k in range(N):
            dW = np.random.normal(
                0,
                np.sqrt(dt)
            )
            X[k+1] = (
                X[k]
                - th * X[k] * dt
                + sigma * dW
            )
        ax.plot(time, X)
    ax.axhline(
        0,
        color="black",
        linestyle="--"
    )
    ax.fill_between(
        time,
        -2 * stat_std,
        2 * stat_std,
        alpha=0.15
    )
    ax.set_title(
        rf"$\theta={th}$"
    )
    ax.grid(alpha=0.3)
axes[0].set_ylabel(r"$X_t$")
plt.suptitle(
    "Effect of Mean-Reversion Speed"
)
plt.tight_layout()
plt.show()
print("\nPart (f)")
for th in thetas:
    var_inf = sigma**2 / (2 * th)
    print(
        f"theta={th}  "
        f"stationary variance={var_inf:.4f}"
    )