# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gvbgo8UnTi0RW7K6T9x1HKWJKSXwUoJD

**Q3: Inventory Random Walks**
*Simulates simple symmetric random walks in dimensions d = 1, 2, 3.*
"""

import numpy as np

np.random.seed(42)
#Simulate a simple symmetric random walk on Z^d.
#At each step, pick one of 2d directions uniformly at random.
#Returns the path as an (n_steps+1) x d array.
def simulate_random_walk(d, n_steps):
    path = np.zeros((n_steps + 1, d), dtype=int)
    for t in range(n_steps):
        direction = np.random.randint(0, 2 * d)
        coord = direction // 2
        sign = 2 * (direction % 2) - 1  # +1 or -1
        path[t + 1] = path[t].copy()
        path[t + 1, coord] += sign
    return path

#Estimate the proportion of paths that return to the origin
#at least once after time 0.
def estimate_return_proportion(d, n_paths, n_steps):
    count_return = 0
    for _ in range(n_paths):
        path = simulate_random_walk(d, n_steps)
        # Check if any position after time 0 is the origin
        if np.any(np.all(path[1:] == 0, axis=1)):
            count_return += 1
    return count_return / n_paths

#e: 1000 paths of length 1000
print("RETURN PROPORTIONS: 1000 paths of length 1000")
n_paths = 1000
n_steps = 1000

for d in [1, 2, 3]:
    prop = estimate_return_proportion(d, n_paths, n_steps)
    print(f"  d = {d}: proportion returning to origin = {prop:.4f}")

#f: Varying path lengths
print("RETURN PROPORTIONS vs PATH LENGTH")
path_lengths = [100, 1000, 10000]

for n in path_lengths:
    print(f"\n  Path length n = {n}:")
    for d in [1, 2, 3]:
        # Use fewer paths for n=10000 to keep runtime reasonable
        np_use = 1000 if n <= 1000 else 500
        prop = estimate_return_proportion(d, np_use, n)
        print(f"    d = {d}: return proportion = {prop:.4f}  ({np_use} paths)")

print("OBSERVATIONS")
print("d=1, d=2: Return proportion approaches 1 as path length increases (recurrent).")
print("d=3:      Return proportion remains bounded well below 1 (transient).")
print("          The theoretical return probability for d=3 is below 1")















