# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18h7FvxUgc28n4J6z4QzRS_bBZ9wfmmIF
"""

import numpy as np
import matplotlib.pyplot as plt

#parameters
S0 = 100
sigma = 0.2
K = 110
N = 100000

#part b
np.random.seed(42)
Z = np.random.normal(0, 1, N)
ST = S0 * np.exp(sigma * Z)
ST

#part c
payoff = np.maximum(ST - K, 0)
payoff

#part d
option_price_estimate = np.mean(payoff)
print("Monte Carlo Estimate of E[(ST-K)+]")
print(f"{option_price_estimate:.4f}")

#part e
plt.figure(figsize=(8,5))
plt.hist(ST, bins=50)
plt.xlabel("Terminal Stock Price ($S_T$)")
plt.ylabel("Frequency")
plt.title("Histogram of Simulated Terminal Stock Prices")
plt.show()

#part f
plt.figure(figsize=(8,5))
plt.hist(payoff, bins=50)
plt.xlabel("Call Option Payoff")
plt.ylabel("Frequency")
plt.title("Histogram of Simulated Call Option Payoffs")
plt.show()

#part g
sigma_values = [0.1, 0.2, 0.3, 0.5]
results = []
for sigma in sigma_values:
    Z = np.random.normal(0, 1, N)
    ST = S0 * np.exp(sigma * Z)
    payoff = np.maximum(ST - K, 0)
    estimate = np.mean(payoff)
    results.append(estimate)
    print(
        f"sigma = {sigma:.1f} -> "
        f"E[(ST-K)+] ≈ {estimate:.4f}"
    )

#part h
plt.figure(figsize=(8,5))
plt.plot(
    sigma_values,
    results,
    marker='o',
    linewidth=2
)
plt.xlabel("Volatility (σ)")
plt.ylabel("Estimated Expected Payoff")
plt.title("Expected Call Payoff vs Volatility")
plt.grid(True)
plt.show()

"""Effect on terminal stock prices

The model is

ST=S0*e^{sigma Z}.

As sigma increases:

* positive values of Z become more amplified;
* negative values of Z become more amplified.

Therefore the distribution of S_T becomes more spread out.

Effect on option payoff

The payoff is

(S_T-K)^+

A call option has:

* limited downside (cannot be negative);
* unlimited upside.

Higher volatility creates more very large values of S_T, increasing the chance of ending above the strike K.

Hence:

Higher volatility implies-
Higher expected call payoff

You should observe numerically that the estimated payoff increases as sigma=0.1,0.2,0.3,0.5 increases.
"""



