# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJmXhj1gjXVDx_M6O3Z6bYVKv_cXERmB
"""

import numpy as np

# Transition Probability Matrix
P = np.array([
    [0.60, 0.30, 0.10, 0.00],
    [0.20, 0.50, 0.20, 0.10],
    [0.10, 0.30, 0.40, 0.20],
    [0.05, 0.15, 0.30, 0.50]
])

print("Transition Matrix P:\n")
print(P)

# Check if rows sum to 1
print("\nRow sums:")
print(P.sum(axis=1))

# Irreducibility Check
# If every state can reach every other state,
# the chain is irreducible.

n = P.shape[0]

reachability = np.zeros((n, n))

for k in range(1, n + 1):
    reachability += np.linalg.matrix_power(P, k)

print("\nReachability Matrix (>0 means reachable):")
print(reachability > 0)

if np.all(reachability > 0):
    print("\nThe Markov chain is IRREDUCIBLE.")
else:
    print("\nThe Markov chain is NOT irreducible.")

# Aperiodicity Check
# If diagonal entries are positive,
# each state has a self-loop => aperiodic.
diag_entries = np.diag(P)

print("\nDiagonal entries:")
print(diag_entries)

if np.all(diag_entries > 0):
    print("\nThe Markov chain is APERIODIC.")
else:
    print("\nThe Markov chain may not be aperiodic.")

# Stationary Distribution
# Solve:
# pi P = pi
# Equivalent:
# P^T pi^T = pi^T

eigenvalues, eigenvectors = np.linalg.eig(P.T)

# Find eigenvalue closest to 1
idx = np.argmin(np.abs(eigenvalues - 1))

# Corresponding eigenvector
pi = eigenvectors[:, idx].real

# Normalize
pi = pi / pi.sum()

print("\nStationary Distribution:")
print(pi)

# Verification

print("\nVerification of piP = pi:")
print("piP =", pi @ P)
print("pi  =", pi)

# Regime Returns
r = np.array([0.012, 0.004, -0.006, -0.025])

print("\nRegime Returns:")
print(r)

# Long-Run Expected Weekly Return

expected_return = pi @ r

print("\nLong-Run Expected Weekly Return:")
print(expected_return)

# Multi-Step Transition Matrix
P10 = np.linalg.matrix_power(P, 10)

print("\n10-Step Transition Matrix P^10:\n")
print(P10)

# Limiting Distribution Approximation

P100 = np.linalg.matrix_power(P, 100)

print("\nApproximate Limiting Matrix P^100:\n")
print(P100)

#Interpretation

states = ["Bull", "Neutral", "Bear", "Crisis"]

print("\nLong-run market regime probabilities:\n")

for i in range(len(states)):
    print(f"{states[i]}: {pi[i]:.4f}")

#d: LONG-RUN AVERAGE WEEKLY RETURN

theoretical_return = pi @ r

print("\n=================================================")

print("(d) LONG-RUN AVERAGE WEEKLY RETURN")

print("=================================================")

print(f"Theoretical Long-Run Weekly Return = {theoretical_return:.6f}")

# e: FRACTION OF TIME IN UNFAVOURABLE REGIMES
# Bear = state 2
# Crisis = state 3

unfavourable_fraction = pi[2] + pi[3]
print("FRACTION OF TIME IN UNFAVOURABLE REGIMES")
print(f"Bear + Crisis Probability = {unfavourable_fraction:.6f}")

#f: SIMULATE MARKOV CHAIN PATH
np.random.seed(42)

n_weeks = 10000

path = np.zeros(n_weeks, dtype=int)

# Start from Bull state

path[0] = 0

for t in range(1, n_weeks):

    current_state = path[t - 1]

    next_state = np.random.choice(

        [0, 1, 2, 3],

        p=P[current_state]

    )

    path[t] = next_state

print("(f) FIRST 20 STATES OF SIMULATED PATH")
print(path[:20])

#g: EMPIRICAL FRACTION OF TIME IN EACH REGIME
empirical_distribution = np.bincount(path, minlength=4) / n_weeks
print("(g) EMPIRICAL vs STATIONARY DISTRIBUTION")
for i in range(len(states)):
    print(f"{states[i]}")
    print(f"Empirical  : {empirical_distribution[i]:.6f}")
    print(f"Theoretical: {pi[i]:.6f}")
    print()

#h: EMPIRICAL AVERAGE WEEKLY RETURN
simulated_returns = r[path]
empirical_average_return = np.mean(simulated_returns)
print("(h) EMPIRICAL vs THEORETICAL RETURN")
print(f"Empirical Average Return   = {empirical_average_return:.6f}")
print(f"Theoretical Average Return = {theoretical_return:.6f}")

#i: CUMULATIVE PORTFOLIO RETURN
cumulative_return = np.cumsum(simulated_returns)
print("(i) FINAL CUMULATIVE RETURN")
print(f"Final Cumulative Return = {cumulative_return[-1]:.6f}")

# PLOT CUMULATIVE RETURN
import matplotlib.pyplot as plt
plt.figure(figsize=(12, 6))
plt.plot(cumulative_return)
plt.xlabel("Week")
plt.ylabel("Cumulative Return")
plt.title("Cumulative Portfolio Return Over Time")
plt.grid(True)
plt.show()



